"""Add garmin oauth support to the users table

Revision ID: b46baef71b83
Revises: 
Create Date: 2025-06-26 20:07:44.647350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46baef71b83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('garmin_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('garmin_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('garmin_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('garmin_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('garmin_connected', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('garmin_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('garmin_scopes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'garmin_scopes')
    op.drop_column('users', 'garmin_connected_at')
    op.drop_column('users', 'garmin_connected')
    op.drop_column('users', 'garmin_user_id')
    op.drop_column('users', 'garmin_token_expires_at')
    op.drop_column('users', 'garmin_refresh_token')
    op.drop_column('users', 'garmin_access_token')
    # ### end Alembic commands ###
